export interface TypeTrabajos {
  'id': string;
  'id-empresa': string;
  'empresa': string;
  'imagen': string;
  'titulo': string;
  'descripcion': string;
  'responsabilidades': string[];
  'requisitos': string[];
  'categorias': string[];
  'beneficios': string[];
  'contrato': string;
  'ubicacion': string;
  'presupuesto-min': number;
  'presupuesto-max': number;
  'fecha-publicacion': string;
  'fecha-inicio': string;
  'fecha-expiracion': string;
  'puntos': number;
  'estado': string;
  'aceptados': string[];
  'nivel': number;
};