export interface TypeEmpresa {
  'id': string;
  'numero-identificacion': string;
  'certificado-registro': string;
  'licencia-comercial': string;
  'nombre': string;
  'telefono': string[];
  'email': string[];
  'contrasena': string;
  'sitio-web': string;
  'direccion': string[];
  'objetivos': string[];
  'redes-sociales': string[];
  'mision': string;
  'vision': string;
  'puntuacion': number;
  'imagen': string;
  'imagen-2': string;
  'verificado': boolean;
};