export interface TypeTrabajadores {
  'id': string;
  'nombres': string;
  'usuario': string;
  'telefono': string;
  'email': string;
  'contrasena': string;
  'redes-sociales': string[];
  'imagen': string;
  'descripcion': string;
  'educacion-primaria': boolean;
  'educacion-secundaria': boolean;
  'titulos': string[];
  'idiomas': string[];
  'certificados': string[];
  'referencias': string[];
  'habilidades': string[];
  'puntos': number;
  'puntuacion': number;
  'saldo': number;
};